DROP TABLE IF EXISTS AIRPLANES;

CREATE TABLE AIRPLANES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  code VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  description VARCHAR(250),
  UNIQUE (code)
);

DROP TABLE IF EXISTS FLIGHTS;

CREATE TABLE FLIGHTS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    type VARCHAR(250),
    origin VARCHAR(250),
    destination VARCHAR(250),
    departure_date TIMESTAMP,
    arrival_date TIMESTAMP,
    airplane_id INT,
    FOREIGN KEY (airplane_id) REFERENCES airplanes(id) ON DELETE CASCADE
)